using System;
using System.ComponentModel;
using MozaPlugin.Devices;

namespace MozaPlugin.UI
{
    /// <summary>
    /// Row view-model for the mBooster tab's device/pedal list — one row per
    /// connected PEDAL (HID axis), not per physical USB connection: a
    /// standalone mBooster contributes one row (AxisIndex 0), a chained unit
    /// hosting several pedals on one connection contributes one row per
    /// detected axis. This is the single selection mechanism for the tab —
    /// it replaces the old separate trio of "Device combo" + "per-axis Pedal
    /// Roles panel" + "Configure pedal combo", which all overlapped the same
    /// "which pedal, which role, which pedal's config shows below" concerns.
    ///
    /// The label is a plain clickable Button (see
    /// <c>MBoosterDeviceRowButtonStyle</c> in SettingsControl.xaml, "selected"
    /// highlight via a DataTrigger on <see cref="IsSelected"/>); clicking it
    /// selects BOTH the physical device AND this specific pedal for the Pedal
    /// Feel/Sim Input/Effects/Calibration cards below — handled by a plain
    /// Click event (<c>MBoosterDeviceRow_Click</c>) reading this row off the
    /// sender's DataContext, deliberately not a WPF selection/grouping
    /// primitive (RadioButton GroupName + TwoWay binding proved unreliable
    /// when generated by an ItemsControl). <see cref="IsSelected"/> is
    /// therefore plain view state, set only by RefreshMBoosterTab.
    ///
    /// The Role combo writes straight to whichever field
    /// <see cref="MozaMBoosterRegistry.ResolveAxisRole"/> actually reads for
    /// THIS row's (identity, axisIndex) pair — <c>MBoosterDeviceSettings.Role</c>
    /// for a standalone pedal, or <c>AxisRoles[axisIndex]</c> for one pedal of
    /// a chain — so every row's combo is always live (no more disabled state).
    /// Role uniqueness (no two rows sharing Throttle/Brake/Clutch) is
    /// enforced by the caller (SettingsControl.xaml.cs), not this class.
    /// </summary>
    internal sealed class MBoosterDeviceRow : INotifyPropertyChanged
    {
        private readonly Action<string, int, MBoosterRole> _onRoleChanged;

        public string Identity { get; }
        public int AxisIndex { get; }
        public string Label { get; }

        public MBoosterDeviceRow(string identity, int axisIndex, string label, bool isSelected, MBoosterRole role,
            Action<string, int, MBoosterRole> onRoleChanged)
        {
            Identity = identity ?? "";
            AxisIndex = axisIndex;
            Label = label ?? "";
            _isSelected = isSelected;
            _roleIndex = (int)role;
            _onRoleChanged = onRoleChanged ?? throw new ArgumentNullException(nameof(onRoleChanged));
        }

        private bool _isSelected;
        /// <summary>Plain view state — drives the row's DataTrigger highlight
        /// only. Set exclusively by RefreshMBoosterTab (never by the click
        /// handler directly) — see MBoosterDeviceRow_Click in
        /// SettingsControl.xaml.cs.</summary>
        public bool IsSelected
        {
            get => _isSelected;
            set
            {
                if (_isSelected == value) return;
                _isSelected = value;
                Raise(nameof(IsSelected));
            }
        }

        private int _roleIndex;
        // 0=Disabled, 1=Throttle, 2=Brake, 3=Clutch — matches the MBoosterRole
        // enum values AND the ComboBox item order in the DataTemplate, so the
        // selected index maps straight to a role.
        public int RoleIndex
        {
            get => _roleIndex;
            set
            {
                if (_roleIndex == value) return;
                _roleIndex = value;
                Raise(nameof(RoleIndex));
                if (value >= 0 && value <= 3)
                    _onRoleChanged(Identity, AxisIndex, (MBoosterRole)value);
            }
        }

        public event PropertyChangedEventHandler? PropertyChanged;
        private void Raise(string name) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
    }
}
