using System;
using System.ComponentModel;
using MozaPlugin.Devices;

namespace MozaPlugin.UI
{
    /// <summary>
    /// Row view-model for the mBooster tab's device/pedal list — one row per
    /// connected PEDAL (HID axis), not per physical USB connection: a
    /// standalone mBooster contributes one row (AxisIndex 0), a chained unit
    /// hosting several pedals on one connection contributes one row per
    /// detected axis. This is the single selection mechanism for the tab —
    /// it replaces the old separate trio of "Device combo" + "per-axis Pedal
    /// Roles panel" + "Configure pedal combo", which all overlapped the same
    /// "which pedal, which role, which pedal's config shows below" concerns.
    ///
    /// The label is a plain clickable Button (see
    /// <c>MBoosterDeviceRowButtonStyle</c> in SettingsControl.xaml, "selected"
    /// highlight via a DataTrigger on <see cref="IsSelected"/>); clicking it
    /// selects BOTH the physical device AND this specific pedal for the Pedal
    /// Feel/Sim Input/Effects/Calibration cards below — handled by a plain
    /// Click event (<c>MBoosterDeviceRow_Click</c>) reading this row off the
    /// sender's DataContext, deliberately not a WPF selection/grouping
    /// primitive (RadioButton GroupName + TwoWay binding proved unreliable
    /// when generated by an ItemsControl). <see cref="IsSelected"/> is
    /// therefore plain view state, set only by RefreshMBoosterTab.
    ///
    /// The Role combo writes straight to whichever field
    /// <see cref="MozaMBoosterRegistry.ResolveAxisRole"/> actually reads for
    /// THIS row's (identity, axisIndex) pair — <c>MBoosterDeviceSettings.Role</c>
    /// for a standalone pedal, or <c>AxisRoles[axisIndex]</c> for one pedal of
    /// a chain — so every row's combo is always live (no more disabled state).
    /// Role uniqueness (no two rows sharing Throttle/Brake/Clutch) is
    /// enforced by the caller (SettingsControl.xaml.cs), not this class.
    /// </summary>
    internal sealed class MBoosterDeviceRow : INotifyPropertyChanged
    {
        private readonly Action<string, int, MBoosterRole> _onRoleChanged;
        private readonly Action<string, string> _onDisplayNameChanged;

        public string Identity { get; }
        public int AxisIndex { get; }

        private string _label;
        /// <summary>Precomputed "{DisplayName} — {ShortIdentity} (COMn)[ —
        /// Pedal N]" text for the row's Button — settable (unlike the rest of
        /// this row's originally-immutable fields) so a DisplayName edit can
        /// update it immediately without waiting for the next 500ms refresh
        /// tick, since DisplayName isn't part of RefreshMBoosterTab's
        /// rowsSignature. See SettingsControl.xaml.cs's
        /// OnMBoosterDeviceRowDisplayNameChanged and the RefreshMBoosterTab
        /// resync branch, both of which recompute and set this.</summary>
        public string Label
        {
            get => _label;
            set
            {
                value ??= "";
                if (_label == value) return;
                _label = value;
                Raise(nameof(Label));
            }
        }

        public MBoosterDeviceRow(string identity, int axisIndex, string label, bool isSelected, MBoosterRole role,
            string displayName,
            Action<string, int, MBoosterRole> onRoleChanged,
            Action<string, string> onDisplayNameChanged)
        {
            Identity = identity ?? "";
            AxisIndex = axisIndex;
            _label = label ?? "";
            _isSelected = isSelected;
            _roleIndex = (int)role;
            _displayName = displayName ?? "";
            _onRoleChanged = onRoleChanged ?? throw new ArgumentNullException(nameof(onRoleChanged));
            _onDisplayNameChanged = onDisplayNameChanged ?? throw new ArgumentNullException(nameof(onDisplayNameChanged));
        }

        private bool _isSelected;
        /// <summary>Plain view state — drives the row's DataTrigger highlight
        /// only. Set exclusively by RefreshMBoosterTab (never by the click
        /// handler directly) — see MBoosterDeviceRow_Click in
        /// SettingsControl.xaml.cs.</summary>
        public bool IsSelected
        {
            get => _isSelected;
            set
            {
                if (_isSelected == value) return;
                _isSelected = value;
                Raise(nameof(IsSelected));
            }
        }

        private int _roleIndex;
        // 0=Disabled, 1=Throttle, 2=Brake, 3=Clutch — matches the MBoosterRole
        // enum values AND the ComboBox item order in the DataTemplate, so the
        // selected index maps straight to a role.
        public int RoleIndex
        {
            get => _roleIndex;
            set
            {
                if (_roleIndex == value) return;
                _roleIndex = value;
                Raise(nameof(RoleIndex));
                if (value >= 0 && value <= 3)
                    _onRoleChanged(Identity, AxisIndex, (MBoosterRole)value);
            }
        }

        private string _displayName;
        /// <summary>User-editable free-text name (optional — helps tell two
        /// mBoosters with the same role apart), bound TwoWay to a TextBox
        /// shown only for the selected row (see the DataTemplate) — this is
        /// per-DEVICE, not per-pedal-axis, so every row sharing this row's
        /// Identity gets the same value; the callback recomputes and reapplies
        /// Label on all of them, not just this one.</summary>
        public string DisplayName
        {
            get => _displayName;
            set
            {
                value ??= "";
                if (_displayName == value) return;
                _displayName = value;
                Raise(nameof(DisplayName));
                _onDisplayNameChanged(Identity, value);
            }
        }

        public event PropertyChangedEventHandler? PropertyChanged;
        private void Raise(string name) => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
    }
}
